### ISSUE TITLE
Method not found with .Net core

### ISSUE THREAD

**Issue by hnviradiya** [holm0563/graphql-schemaGenerator#4]
When I use with ASP .Net core I get below error. (HTML file is attached in zip for better readability)

An unhandled exception occurred while processing the request.
MissingMethodException: Method not found: 'GraphQL.Types.FieldType GraphQL.Types.ComplexGraphType`1.FieldAsync(System.Type, System.String, System.String, GraphQL.Types.QueryArguments, System.Func`2<GraphQL.Types.ResolveFieldContext`1<!0>,System.Object>, System.String)'.
GraphQL.SchemaGenerator.SchemaGenerator.CreateSchema(IEnumerable<FieldDefinition> definitions) in SchemaGenerator.cs, line 148

Stack Query Cookies Headers
MissingMethodException: Method not found: 'GraphQL.Types.FieldType GraphQL.Types.ComplexGraphType`1.FieldAsync(System.Type, System.String, System.String, GraphQL.Types.QueryArguments, System.Func`2<GraphQL.Types.ResolveFieldContext`1<!0>,System.Object>, System.String)'.
GraphQL.SchemaGenerator.SchemaGenerator.CreateSchema(IEnumerable<FieldDefinition> definitions) in SchemaGenerator.cs
+
        }
GraphQL.SchemaGenerator.SchemaGenerator.CreateSchema(Type[] types) in SchemaGenerator.cs
+
            return CreateSchema(CreateDefinitions(types));
sampleprojectweb.Controllers.GraphQLController.Post(GraphQLQuery query) in GraphQLController.cs
+
            var schema = schemaGenerator.CreateSchema(typeof(GraphRoot));
Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor+TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, object controller, object[] arguments)
System.Threading.Tasks.ValueTask<TResult>.get_Result()
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)
Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

Show raw exception details
[GraphQL Issue.zip](https://github.com/holm0563/graphql-schemaGenerator/files/2998070/GraphQL.Issue.zip)

**Comment by kevinsnijder** [comment]
@hnviradiya did you close this because you fixed it? If so, how did you manage to fix it?

**Comment by hnviradiya** [comment]
@kevinsnijder I have totally forgotten what was this issue and how was this fixed later. as currently (and that time also I was not using this, just was trying, so it may possible that I have not fixed this at all) I am not using this library or graphql at all in my project. and back then also I have not commited any code to my repo using this library. So I am totally don't know what was this about. Sorry that you had to hear this. :(

**Comment by kevinsnijder** [comment]
No worries, thanks for responding!
